language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  repo: genesixx/genesixx.github.io
  on:
    branch: master
before_script:
  - 'npm run build'
