language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  repo: eleboucher/eleboucher.github.io
  on:
    branch: master
before_script:
  - yarn build
after_success:
  - yarn coveralls
